// owner: a3-distribution-and-readme
//
// ----------------------------------------------------------------------------
// a3's DEFINITION OF DONE IS WRITTEN AS THINGS A CLEAN MACHINE WOULD OBSERVE.
// ----------------------------------------------------------------------------
// "on a clean Windows, a clean macOS and a clean Linux host that has never
// built the product, each channel installs a working binary"; "each install
// script aborts, with a clear message and a non-zero exit, when pointed at a
// deliberately corrupted asset"; "running it twice leaves one working binary";
// "`--version X.Y.Z` installs that exact version".
//
// Every one of those needs a PUBLISHED RELEASE to install from, and this
// project's release workflow publishes under the project's name (D10, and
// `07-security.md` operational requirement 7). A gate whose only test is "cut a
// release and try it" is a gate first exercised by the release that needed it.
//
// So `common::build_release` builds a synthetic release -- five archives laid
// out exactly as the real ones are, plus a `SHA256SUMS` generated by
// `release.sh sha256`, the same code the real release calls -- and BOTH INSTALL
// SCRIPTS ARE RUN AGAINST IT, END TO END, on every pull request, on all three
// operating systems. Nothing is published and no credential is needed.
//
// This is possible because each script accepts a local directory as its asset
// base. That is not a test hook bolted on: it is what an air-gapped or mirrored
// install looks like, and it is documented in both scripts' headers.
//
// ----------------------------------------------------------------------------
// WHAT THIS FILE CANNOT REACH, RECORDED RATHER THAN PAPERED OVER.
// ----------------------------------------------------------------------------
//   * The real https://github.com/.../releases/latest/download address. What is
//     driven here is the resolution and verification logic; the network hop is
//     `curl`'s and `Invoke-WebRequest`'s.
//   * "No Gatekeeper block and no SmartScreen warning." Those are properties of
//     a quarantine flag that only a browser sets, on OS versions no CI matrix
//     here runs. `the_readme_advertises_no_download_that_is_not_a_terminal_command`
//     in `readme_disclosure.rs` guards the thing that would BREAK it -- a
//     download button reappearing -- which is the half that is checkable.
//   * A real cross-architecture binary. The stand-in is a `/bin/sh` script that
//     echoes its version, so "the installed file still runs" is a real
//     assertion; "the aarch64 build runs on aarch64" is not.

mod common;

use common::{
    FixtureRelease, TARGETS, bash_program, build_release, install_script, posix, repository_root,
    run_bash, substitute_payload,
};

use std::path::{Path, PathBuf};
use std::process::Command;

use tempfile::TempDir;

// ----------------------------------------------------------------------------
// Driving install.sh.
// ----------------------------------------------------------------------------

/// A platform the installer is being asked to believe it is on.
struct Host {
    uname_s: &'static str,
    uname_m: &'static str,
}

const LINUX_X64: Host = Host {
    uname_s: "Linux",
    uname_m: "x86_64",
};

fn run_install_sh(
    host: &Host,
    base: &Path,
    install_dir: &Path,
    arguments: &[&str],
) -> (bool, String) {
    run_bash(
        &install_script("install.sh"),
        arguments,
        &[
            ("RUNNER_MANAGER_INSTALL_UNAME_S", host.uname_s),
            ("RUNNER_MANAGER_INSTALL_UNAME_M", host.uname_m),
            ("RUNNER_MANAGER_INSTALL_BASE_URL", &posix(base)),
            ("RUNNER_MANAGER_INSTALL_DIR", &posix(install_dir)),
        ],
    )
}

/// One `key=value` line out of `--print-plan`.
fn plan_value(output: &str, key: &str) -> String {
    let prefix = format!("{key}=");
    output
        .lines()
        .find_map(|line| line.trim().strip_prefix(&prefix))
        .unwrap_or_else(|| panic!("--print-plan printed no `{key}=` line:\n{output}"))
        .to_string()
}

/// Runs the installed stand-in binary and returns what it printed.
///
/// Through bash, so that the one assertion that matters -- the file that landed
/// is intact and still executes -- holds on Windows too, where the fixture's
/// `#!/bin/sh` payload cannot be started by the OS directly.
fn run_installed(binary: &Path) -> String {
    let output = Command::new(bash_program())
        .arg(posix(binary))
        .output()
        .unwrap_or_else(|err| panic!("cannot run the installed binary: {err}"));
    assert!(
        output.status.success(),
        "the installed binary did not run: {}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

fn installed_entries(directory: &Path) -> Vec<String> {
    let mut names: Vec<String> = std::fs::read_dir(directory)
        .unwrap_or_else(|err| panic!("cannot list {}: {err}", directory.display()))
        .map(|entry| {
            entry
                .expect("a directory entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    names.sort();
    names
}

// ----------------------------------------------------------------------------
// install.sh -- choosing an artifact.
// ----------------------------------------------------------------------------

#[test]
fn install_sh_selects_the_right_artifact_for_every_supported_platform() {
    // `uname -m` does not report one spelling per architecture, and the two
    // spellings do not come from the same operating systems: macOS says
    // `arm64`, Linux says `aarch64`, and a handful of Linux userlands say
    // `amd64` where the kernel says `x86_64`. A mapping that knows one of each
    // pair installs nothing on half the hosts it was written for.
    let temporary = TempDir::new().expect("a temporary directory");
    let base = temporary.path();

    for (uname_s, uname_m, expected) in [
        ("Linux", "x86_64", "x86_64-unknown-linux-gnu"),
        ("Linux", "amd64", "x86_64-unknown-linux-gnu"),
        ("Linux", "aarch64", "aarch64-unknown-linux-gnu"),
        ("Linux", "arm64", "aarch64-unknown-linux-gnu"),
        ("Darwin", "arm64", "aarch64-apple-darwin"),
        ("Darwin", "aarch64", "aarch64-apple-darwin"),
        ("Darwin", "x86_64", "x86_64-apple-darwin"),
    ] {
        let host = Host { uname_s, uname_m };
        let (ok, output) = run_install_sh(&host, base, base, &["--print-plan"]);
        assert!(ok, "install.sh refused {uname_s}/{uname_m}:\n{output}");
        assert_eq!(
            plan_value(&output, "target"),
            expected,
            "install.sh maps {uname_s}/{uname_m} to the wrong artifact:\n{output}"
        );
    }
}

#[test]
fn install_sh_refuses_a_platform_it_does_not_recognise() {
    // An unrecognised platform must be a refusal and not a guess. "Probably the
    // x86_64 one" produces a binary that fails to exec with a message about the
    // dynamic loader, which is a far worse thing to hand a user than a sentence
    // naming what was seen.
    let temporary = TempDir::new().expect("a temporary directory");
    let base = temporary.path();

    for (uname_s, uname_m, must_mention, why) in [
        (
            "SunOS",
            "x86_64",
            "SunOS",
            "the rejection has to name the value it saw, or an operator cannot \
             tell a wrong override from an unsupported host",
        ),
        (
            "Linux",
            "riscv64",
            "cargo install",
            "an unsupported architecture still has a way in -- building from \
             source -- and the refusal is where to say so",
        ),
        (
            "MINGW64_NT-10.0-26100",
            "x86_64",
            "install.ps1",
            "a Windows user piping this into Git Bash is the likeliest way to \
             reach install.sh by mistake, and it must point at the right script \
             rather than install a Linux binary that cannot run",
        ),
    ] {
        let host = Host { uname_s, uname_m };
        let (ok, output) = run_install_sh(&host, base, base, &["--print-plan"]);
        assert!(
            !ok,
            "install.sh accepted {uname_s}/{uname_m}, which it publishes no \
             artifact for:\n{output}"
        );
        assert!(
            output.contains(must_mention),
            "the refusal for {uname_s}/{uname_m} does not mention \
             `{must_mention}`: {why}\n{output}"
        );
    }
}

#[test]
fn install_sh_defaults_to_the_documented_directory() {
    // Load-bearing rather than tidiness: `service install` records the
    // ABSOLUTE path of the binary (`05-infrastructure.md`, service behaviour
    // 6), so an install location that moves breaks unattended start. This is
    // the assertion that notices the default being "improved" to
    // /usr/local/bin (needs root) or to a toolchain prefix (moves).
    let temporary = TempDir::new().expect("a temporary directory");
    // A distinctive name, because the assertion below matches on the tail of
    // the path rather than on all of it: Git Bash rewrites `HOME` on the way
    // into the script, mapping the Windows temp directory onto `/tmp`, so the
    // string the script prints is not the string this test passed in.
    let home = temporary.path().join("fixture-home");
    std::fs::create_dir_all(&home).expect("a fake home");

    let (ok, output) = run_bash(
        &install_script("install.sh"),
        &["--print-plan"],
        &[
            ("RUNNER_MANAGER_INSTALL_UNAME_S", "Linux"),
            ("RUNNER_MANAGER_INSTALL_UNAME_M", "x86_64"),
            ("RUNNER_MANAGER_INSTALL_BASE_URL", &posix(temporary.path())),
            ("HOME", &posix(&home)),
            // Deliberately unset, so the default is what is measured.
            ("RUNNER_MANAGER_INSTALL_DIR", ""),
        ],
    );
    assert!(ok, "install.sh --print-plan failed:\n{output}");

    let directory = plan_value(&output, "install_dir");
    assert!(
        directory.ends_with("/fixture-home/.local/bin"),
        "install.sh must default to `$HOME/.local/bin`, and it must be the HOME \
         it was given rather than a hardcoded path. `~/.local/bin` is chosen \
         because it belongs to the user rather than to a toolchain, so it does \
         not move when the operator switches Node or Rust versions -- which an \
         installed service's recorded absolute path cannot survive. \
         Got `{directory}`.\n{output}"
    );
    assert_eq!(
        plan_value(&output, "binary"),
        format!("{directory}/runner-manager"),
        "the plan's binary path must be the install directory plus the binary \
         name; that path is what `service install` records\n{output}"
    );
}

#[test]
fn install_sh_rejects_a_version_that_is_not_x_y_z() {
    let temporary = TempDir::new().expect("a temporary directory");
    let base = temporary.path();

    for (argument, why) in [
        ("1.2", "a Cargo version has exactly three components"),
        ("v1.2.3", "the `v` belongs to the tag, not to the version"),
        ("abc", "not a version at all"),
        ("1.2.3-rc1", "pre-releases are not a v1 channel (D12)"),
    ] {
        let (ok, output) = run_install_sh(&LINUX_X64, base, base, &["--version", argument]);
        assert!(
            !ok,
            "install.sh accepted --version {argument}: {why}\n{output}"
        );
        assert!(
            output.contains("is not X.Y.Z") || output.contains("belongs to the tag"),
            "the refusal of --version {argument} must say what is wrong with \
             it, not fail later as a download error:\n{output}"
        );
    }
}

// ----------------------------------------------------------------------------
// install.sh -- installing.
// ----------------------------------------------------------------------------

struct Installed {
    _temporary: TempDir,
    release: FixtureRelease,
    directory: PathBuf,
}

impl Installed {
    fn binary(&self) -> PathBuf {
        self.directory.join("runner-manager")
    }
}

fn prepare(version: &str) -> Installed {
    let temporary = TempDir::new().expect("a temporary directory");
    let release = build_release(temporary.path(), version);
    let directory = temporary.path().join("bin");
    Installed {
        _temporary: temporary,
        release,
        directory,
    }
}

#[test]
fn install_sh_verifies_the_published_digest_and_installs_a_working_binary() {
    let fixture = prepare("1.2.3");
    let (ok, output) = run_install_sh(&LINUX_X64, &fixture.release.assets, &fixture.directory, &[]);
    assert!(ok, "install.sh failed on a good release:\n{output}");

    // The digest is not merely computed, it is REPORTED. A user who never sees
    // this line has no way to tell a verified install from an unverified one.
    assert!(
        output.contains("SHA-256 OK"),
        "install.sh installed without reporting that it verified the archive:\n{output}"
    );

    let binary = fixture.binary();
    assert!(
        binary.is_file(),
        "install.sh reported success and installed nothing to {}",
        fixture.directory.display()
    );
    assert_eq!(
        run_installed(&binary),
        fixture.release.expected_output("x86_64-unknown-linux-gnu"),
        "the installed file is not the binary from the archive"
    );

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&binary)
            .expect("metadata")
            .permissions()
            .mode();
        assert!(
            mode & 0o111 != 0,
            "the installed binary is not executable (mode {mode:o}). A file \
             that has to be chmod'ed by hand is not an install."
        );
    }

    // The version is discovered from SHA256SUMS rather than hardcoded, which is
    // why the script never needs editing at release time.
    assert!(
        output.contains("Release 1.2.3"),
        "install.sh must report the version it resolved from SHA256SUMS:\n{output}"
    );
}

#[test]
fn install_sh_aborts_on_a_corrupted_archive_and_leaves_the_previous_install_alone() {
    // ------------------------------------------------------------------------
    // THE ARCHIVE IS SUBSTITUTED, NOT DAMAGED. See `common::substitute_payload`:
    // a damaged one is refused by `tar` before the digest is ever consulted, so
    // a script with no checksum check would pass this test too.
    //
    // THE SECOND HALF IS THE ONE THAT IS EASY TO GET WRONG.
    // ------------------------------------------------------------------------
    // "Aborts on a corrupted asset" is satisfied by a script that deletes the
    // old binary, downloads, discovers the mismatch and exits -- and that is a
    // worse outcome than not running it at all: a failed UPGRADE would take out
    // a working install and the host's boot-start service with it. So this
    // installs a good version first and asserts it still runs afterwards.
    let fixture = prepare("1.2.3");
    let (ok, output) = run_install_sh(&LINUX_X64, &fixture.release.assets, &fixture.directory, &[]);
    assert!(ok, "the first install must succeed:\n{output}");
    let before = run_installed(&fixture.binary());

    substitute_payload(&fixture.release, "x86_64-unknown-linux-gnu");

    let (ok, output) = run_install_sh(&LINUX_X64, &fixture.release.assets, &fixture.directory, &[]);
    assert!(
        !ok,
        "install.sh installed an archive whose digest does not match the \
         published one. `07-security.md` lists artifact tampering in transit as \
         a threat whose only control is this check.\n{output}"
    );
    assert!(
        output.contains("CHECKSUM MISMATCH"),
        "the abort must say plainly what went wrong; a user seeing only a \
         non-zero exit will assume a network problem and retry forever:\n{output}"
    );
    assert!(
        output.contains("nothing has been\ninstalled") || output.contains("nothing has been"),
        "the abort must tell the user that nothing was installed:\n{output}"
    );

    assert_eq!(
        run_installed(&fixture.binary()),
        before,
        "a failed install replaced or damaged the binary that was already \
         working. A failed upgrade must be a no-op."
    );
    assert_eq!(
        installed_entries(&fixture.directory),
        vec!["runner-manager".to_string()],
        "the aborted install left a staging file behind in the install \
         directory"
    );
}

#[test]
fn install_sh_is_idempotent() {
    let fixture = prepare("1.2.3");
    for attempt in 1..=2 {
        let (ok, output) =
            run_install_sh(&LINUX_X64, &fixture.release.assets, &fixture.directory, &[]);
        assert!(ok, "install.sh failed on attempt {attempt}:\n{output}");
    }

    assert_eq!(
        installed_entries(&fixture.directory),
        vec!["runner-manager".to_string()],
        "running install.sh twice must leave exactly one working binary and no \
         staging or backup files"
    );
    assert_eq!(
        run_installed(&fixture.binary()),
        fixture.release.expected_output("x86_64-unknown-linux-gnu"),
        "the binary left by the second run does not work"
    );
}

#[test]
fn install_sh_installs_the_exact_version_asked_for_or_nothing() {
    let fixture = prepare("1.2.3");

    // The version that IS published installs.
    let (ok, output) = run_install_sh(
        &LINUX_X64,
        &fixture.release.assets,
        &fixture.directory,
        &["--version", "1.2.3"],
    );
    assert!(ok, "--version 1.2.3 must install release 1.2.3:\n{output}");
    assert!(
        fixture.binary().is_file(),
        "nothing was installed:\n{output}"
    );

    // One that is not must be a refusal, and it must name both versions. This
    // is the case a remote 404 would normally catch and a local or mirrored
    // asset directory would not -- so the check is on the resolved asset name,
    // not on the transport.
    let (ok, output) = run_install_sh(
        &LINUX_X64,
        &fixture.release.assets,
        &fixture.directory,
        &["--version", "9.9.9"],
    );
    assert!(
        !ok,
        "install.sh installed 1.2.3 when it was asked for 9.9.9:\n{output}"
    );
    assert!(
        output.contains("9.9.9") && output.contains("1.2.3"),
        "the refusal must name what was asked for and what is available:\n{output}"
    );
}

#[test]
fn install_sh_refuses_a_release_that_publishes_nothing_for_this_platform() {
    // The install script derives the asset name from SHA256SUMS instead of
    // constructing it, so "this release has no build for you" is a state it can
    // actually observe. It must be a refusal: constructing the name anyway
    // produces a 404 that reads like an outage.
    let fixture = prepare("1.2.3");
    let sums = std::fs::read_to_string(fixture.release.sums()).expect("the fixture SHA256SUMS");
    let thinned: String = sums
        .lines()
        .filter(|line| !line.contains("x86_64-unknown-linux-gnu"))
        .map(|line| format!("{line}\n"))
        .collect();
    assert!(
        thinned.lines().count() == TARGETS.len() - 1,
        "the fixture SHA256SUMS did not lose exactly one line; the assertion \
         below would not be testing what it says"
    );
    std::fs::write(fixture.release.sums(), thinned).expect("rewriting SHA256SUMS");

    let (ok, output) = run_install_sh(&LINUX_X64, &fixture.release.assets, &fixture.directory, &[]);
    assert!(!ok, "install.sh installed something anyway:\n{output}");
    assert!(
        output.contains("lists no archive for x86_64-unknown-linux-gnu"),
        "the refusal must name the platform the release is missing:\n{output}"
    );
}

// ----------------------------------------------------------------------------
// Both scripts -- properties that are shapes in the source.
// ----------------------------------------------------------------------------

/// A script with its comments removed.
///
/// ----------------------------------------------------------------------------
/// SCANNED OVER EXECUTABLE TEXT, NOT OVER THE FILE -- a2's LESSON, AGAIN.
/// ----------------------------------------------------------------------------
/// `release_workflow.rs` learned this the hard way: the release workflow is
/// REQUIRED to document `git tag -d` as operator recovery, so a whole-file
/// search for it forced the workflow to choose between documenting the recovery
/// and passing its own test. The same trap is here. Both install scripts are
/// required to explain why there is no `--skip-verify` and why a bashism would
/// break `sh` -- which means both files necessarily contain the exact strings
/// the scans below look for, in comments, as prose for a human.
///
/// What matters is not whether the string appears but whether it is EXECUTED.
fn executable_text(name: &str) -> String {
    let source = std::fs::read_to_string(install_script(name))
        .unwrap_or_else(|err| panic!("cannot read {name}: {err}"));

    // PowerShell's block comment first: `<# ... #>` spans lines and holds each
    // script's whole header.
    let mut without_blocks = String::new();
    let mut rest = source.as_str();
    while let Some(open) = rest.find("<#") {
        without_blocks.push_str(&rest[..open]);
        match rest[open..].find("#>") {
            Some(close) => rest = &rest[open + close + 2..],
            None => {
                rest = "";
                break;
            }
        }
    }
    without_blocks.push_str(rest);

    without_blocks
        .lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn neither_installer_offers_a_way_to_skip_the_checksum() {
    // ------------------------------------------------------------------------
    // THERE IS NO FLAG FOR THIS, AND THERE MUST NEVER BE ONE.
    // ------------------------------------------------------------------------
    // A verification that can be turned off is a verification an attacker can
    // ask to have turned off -- in a forum post, in a stale blog, in an
    // "if the checksum fails, try --no-verify" answer. Such a flag is always
    // added for a good reason (a mirror that is briefly stale, a corporate
    // proxy rewriting bodies) and it is the reason the control stops existing.
    for name in ["install.sh", "install.ps1"] {
        let source = executable_text(name).to_lowercase();
        assert!(
            source.contains("sha256sums"),
            "{name}'s executable text never reads SHA256SUMS, so the absences \
             below would be vacuous -- a script that verifies nothing trivially \
             has no flag to switch verification off"
        );
        for forbidden in [
            "--skip-verify",
            "--no-verify",
            "--insecure",
            "-skipverify",
            "-noverify",
            "-insecure",
        ] {
            assert!(
                !source.contains(forbidden),
                "{name} accepts `{forbidden}`. The SHA-256 check is the only \
                 control `07-security.md` lists against a tampered release \
                 artifact; it does not get an off switch."
            );
        }
    }
}

#[test]
fn install_sh_stays_runnable_by_a_posix_shell() {
    // The documented command is `curl ... | sh`. On Debian and Ubuntu that is
    // `dash`; on Alpine it is BusyBox ash. Neither has `[[`, arrays, or
    // `${var,,}`, and a bashism here fails on exactly the hosts the script
    // exists to serve -- halfway through, after the download.
    //
    // The test suite runs this script under bash, which would accept every one
    // of these happily, so a static scan is the only thing that notices.
    let raw = std::fs::read_to_string(install_script("install.sh")).expect("install.sh");
    assert!(
        raw.starts_with("#!/bin/sh\n"),
        "install.sh must declare `#!/bin/sh`: the README documents piping it \
         into `sh`, and the shebang is what a reader checks it against"
    );

    // Scanned over executable text: the script's own header explains why a
    // bashism would break `sh`, and naming them there must not fail this.
    let source = executable_text("install.sh");
    // Positive guard: a file this scan could not read would satisfy every
    // absence below.
    assert!(
        source.contains("case \"$uname_s\" in"),
        "install.sh no longer looks like the script this scan was written \
         against; the bashism assertions below would be checking nothing"
    );

    for (bashism, why) in [
        ("<<<", "here-strings are bash-only"),
        (
            "declare ",
            "`declare` is bash-only; POSIX has no equivalent",
        ),
        ("${!", "indirect expansion is bash-only"),
        (
            ",,}",
            "case conversion in a parameter expansion is bash-only",
        ),
        (
            "^^}",
            "case conversion in a parameter expansion is bash-only",
        ),
        (
            "function ",
            "`function name()` is bash syntax; POSIX is `name()`",
        ),
        ("+=(", "arrays are bash-only"),
        (
            "local -",
            "`local -a`/`local -n` are bash-only; plain `local` is fine",
        ),
    ] {
        assert!(
            !source.contains(bashism),
            "install.sh uses `{bashism}`: {why}. It runs under `sh`, which on \
             Debian and Ubuntu is dash and on Alpine is BusyBox ash."
        );
    }

    // ------------------------------------------------------------------------
    // TWO PATTERNS NEED MORE THAN A SUBSTRING, BECAUSE awk IS EMBEDDED HERE.
    // ------------------------------------------------------------------------
    // `[[` is a bash keyword AND the opening of a POSIX character class, and
    // `==` is a bashism in `[ ... ]` AND ordinary awk. install.sh embeds an awk
    // program to read SHA256SUMS, so a bare substring search reports the awk as
    // a shell bug -- and the fix somebody reaches for is to weaken the test.
    for (number, line) in source.lines().enumerate() {
        let number = number + 1;
        assert!(
            !line.replace("[[:", "").contains("[["),
            "install.sh line {number} uses bash's `[[`; POSIX test is `[`:\n  {line}"
        );
        // A shell test with `==` is written `[ x == y ]`, so the line carries a
        // bracket followed by a space. `field[1] == 2` inside awk does not.
        assert!(
            !(line.contains(" == ") && line.contains("[ ")),
            "install.sh line {number} compares with `==` inside `[ ]`; POSIX \
             test compares with `=`:\n  {line}"
        );
    }
}

// ----------------------------------------------------------------------------
// install.ps1.
// ----------------------------------------------------------------------------

/// The PowerShell that runs install.ps1.
///
/// `pwsh` first, then Windows PowerShell. Both are supported hosts and the
/// script is written for 5.1 deliberately -- a clean Windows machine has 5.1
/// and no PowerShell 7, and the Definition of Done names a clean Windows host
/// with no Node installed as a case `irm ... | iex` must serve.
fn powershell_program() -> Option<PathBuf> {
    for candidate in ["pwsh", "pwsh.exe", "powershell.exe"] {
        if let Some(found) = find_program(candidate) {
            return Some(found);
        }
    }
    None
}

fn find_program(program: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|directory| directory.join(program))
        .find(|candidate| candidate.is_file())
}

/// Resolves PowerShell, or explains why the caller may stop.
///
/// PowerShell 7 is preinstalled on all three GitHub-hosted runner images and
/// Windows always has 5.1, so its absence is a developer-machine condition and
/// not a CI one. Skipping quietly wherever it is missing would make this an
/// assertion that could vanish from CI unnoticed, so `CI` being set turns the
/// skip back into a failure.
fn powershell_or_skip() -> Option<PathBuf> {
    if let Some(found) = powershell_program() {
        return Some(found);
    }
    // Written as a branch rather than `assert!(!cfg!(windows), ...)`, which
    // clippy reads -- correctly -- as an assertion on a constant.
    if cfg!(windows) {
        panic!(
            "no PowerShell found on a Windows host. Windows PowerShell 5.1 is \
             part of the operating system, so this is a broken PATH rather than \
             a missing dependency."
        );
    }
    assert!(
        std::env::var_os("CI").is_none(),
        "no `pwsh` on PATH in CI. PowerShell 7 is preinstalled on GitHub's \
         ubuntu and macOS runner images; if that stops being true, install it \
         in the workflow rather than letting install.ps1 go untested."
    );
    eprintln!(
        "SKIPPED: no PowerShell on PATH. install.ps1 is exercised on Windows \
         and in CI; install `pwsh` to run it here."
    );
    None
}

fn run_install_ps1(
    shell: &Path,
    base: &Path,
    install_dir: &Path,
    arguments: &[&str],
) -> (bool, String) {
    let script = install_script("install.ps1");
    let mut command = Command::new(shell);
    command.arg("-NoProfile").arg("-NonInteractive");
    if cfg!(windows) {
        // `-ExecutionPolicy` applies to Windows only; pwsh on Linux rejects it.
        command.arg("-ExecutionPolicy").arg("Bypass");
    }
    command.arg("-File").arg(&script);
    command.arg("-BaseUrl").arg(base);
    command.arg("-Dir").arg(install_dir);
    command.args(arguments);
    command.current_dir(repository_root());

    let output = command
        .output()
        .unwrap_or_else(|err| panic!("cannot run install.ps1: {err}"));
    (
        output.status.success(),
        format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ),
    )
}

#[test]
fn install_ps1_selects_the_windows_artifact_for_both_architectures() {
    let Some(shell) = powershell_or_skip() else {
        return;
    };
    let temporary = TempDir::new().expect("a temporary directory");
    let base = temporary.path();

    // Only one Windows target is published, and Windows-on-ARM is served by it
    // through the x64 emulation layer. npm cannot do that -- it will not
    // install a `"cpu": ["x64"]` package onto an arm64 host -- so this is the
    // one platform where the install script reaches a user npm cannot.
    for architecture in ["AMD64", "ARM64"] {
        let (ok, output) =
            run_install_ps1(&shell, base, base, &["-PrintPlan", "-Arch", architecture]);
        assert!(ok, "install.ps1 refused {architecture}:\n{output}");
        assert_eq!(
            plan_value(&output, "target"),
            "x86_64-pc-windows-msvc",
            "install.ps1 maps {architecture} to the wrong artifact:\n{output}"
        );
    }

    // 32-bit x86 publishes nothing, so it must be a refusal rather than a
    // silent x64 install that fails to load.
    let (ok, output) = run_install_ps1(&shell, base, base, &["-PrintPlan", "-Arch", "x86"]);
    assert!(
        !ok,
        "install.ps1 accepted a 32-bit x86 host, which publishes no artifact:\n{output}"
    );
    assert!(
        output.contains("cargo install"),
        "the refusal must point at the way in that still exists:\n{output}"
    );
}

#[test]
fn install_ps1_defaults_to_the_documented_directory() {
    let Some(shell) = powershell_or_skip() else {
        return;
    };
    let temporary = TempDir::new().expect("a temporary directory");
    let local_app_data = temporary.path().join("LocalAppData");
    std::fs::create_dir_all(&local_app_data).expect("a fake LOCALAPPDATA");

    let script = install_script("install.ps1");
    let mut command = Command::new(&shell);
    command.arg("-NoProfile").arg("-NonInteractive");
    if cfg!(windows) {
        command.arg("-ExecutionPolicy").arg("Bypass");
    }
    command.arg("-File").arg(&script);
    command.arg("-BaseUrl").arg(temporary.path());
    command.arg("-PrintPlan");
    command.env("LOCALAPPDATA", &local_app_data);
    command.env("RUNNER_MANAGER_INSTALL_DIR", "");
    command.current_dir(repository_root());

    let output = command.output().expect("cannot run install.ps1");
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.status.success(),
        "install.ps1 --print-plan failed:\n{text}"
    );

    let directory = plan_value(&text, "install_dir");
    // Asserted on the shape rather than on an exact string: `Join-Path` uses
    // the host's separator, and this test also runs on Linux and macOS.
    assert!(
        directory.starts_with(&local_app_data.to_string_lossy().to_string()),
        "install.ps1 must default under %LOCALAPPDATA%, got {directory}"
    );
    assert!(
        directory.contains("Programs") && directory.ends_with("runner-manager"),
        "install.ps1 must default to %LOCALAPPDATA%\\Programs\\runner-manager. \
         It is per-user, needs no elevation, and does not move when a toolchain \
         moves -- which an installed service's recorded absolute path cannot \
         survive. Got {directory}"
    );
}

#[test]
fn install_ps1_verifies_the_published_digest_and_installs() {
    let Some(shell) = powershell_or_skip() else {
        return;
    };
    let fixture = prepare("1.2.3");
    let (ok, output) = run_install_ps1(&shell, &fixture.release.assets, &fixture.directory, &[]);
    assert!(ok, "install.ps1 failed on a good release:\n{output}");
    assert!(
        output.contains("SHA-256 OK"),
        "install.ps1 installed without reporting that it verified the \
         archive:\n{output}"
    );

    let binary = fixture.directory.join("runner-manager.exe");
    assert!(
        binary.is_file(),
        "install.ps1 reported success and installed nothing to {}",
        fixture.directory.display()
    );
    assert_eq!(
        std::fs::read(&binary).expect("the installed binary"),
        std::fs::read(
            fixture
                .release
                .staged("x86_64-pc-windows-msvc")
                .join("runner-manager.exe")
        )
        .expect("the staged binary"),
        "the installed file is not byte-identical to the one in the archive"
    );
    assert!(
        output.contains("Release 1.2.3"),
        "install.ps1 must report the version it resolved from SHA256SUMS:\n{output}"
    );
}

#[test]
fn install_ps1_aborts_on_a_corrupted_archive_and_leaves_the_previous_install_alone() {
    let Some(shell) = powershell_or_skip() else {
        return;
    };
    let fixture = prepare("1.2.3");
    let (ok, output) = run_install_ps1(&shell, &fixture.release.assets, &fixture.directory, &[]);
    assert!(ok, "the first install must succeed:\n{output}");

    let binary = fixture.directory.join("runner-manager.exe");
    let before = std::fs::read(&binary).expect("the installed binary");

    substitute_payload(&fixture.release, "x86_64-pc-windows-msvc");

    let (ok, output) = run_install_ps1(&shell, &fixture.release.assets, &fixture.directory, &[]);
    assert!(
        !ok,
        "install.ps1 installed an archive whose digest does not match the \
         published one:\n{output}"
    );
    assert!(
        output.contains("CHECKSUM MISMATCH"),
        "the abort must say plainly what went wrong:\n{output}"
    );
    assert_eq!(
        std::fs::read(&binary).expect("the installed binary"),
        before,
        "a failed install replaced or damaged a binary that was already \
         working. A failed upgrade must be a no-op."
    );
    assert_eq!(
        installed_entries(&fixture.directory),
        vec!["runner-manager.exe".to_string()],
        "the aborted install left a staging file behind"
    );
}

#[test]
fn install_ps1_is_idempotent_and_pins_the_version_asked_for() {
    let Some(shell) = powershell_or_skip() else {
        return;
    };
    let fixture = prepare("1.2.3");

    for attempt in 1..=2 {
        let (ok, output) =
            run_install_ps1(&shell, &fixture.release.assets, &fixture.directory, &[]);
        assert!(ok, "install.ps1 failed on attempt {attempt}:\n{output}");
    }
    assert_eq!(
        installed_entries(&fixture.directory),
        vec!["runner-manager.exe".to_string()],
        "running install.ps1 twice must leave exactly one binary and no \
         staging files"
    );

    let (ok, output) = run_install_ps1(
        &shell,
        &fixture.release.assets,
        &fixture.directory,
        &["-Version", "9.9.9"],
    );
    assert!(
        !ok,
        "install.ps1 installed 1.2.3 when it was asked for 9.9.9:\n{output}"
    );
    assert!(
        output.contains("9.9.9") && output.contains("1.2.3"),
        "the refusal must name what was asked for and what is available:\n{output}"
    );

    let (ok, output) = run_install_ps1(
        &shell,
        &fixture.release.assets,
        &fixture.directory,
        &["-Version", "v1.2.3"],
    );
    assert!(!ok, "install.ps1 accepted -Version v1.2.3:\n{output}");
    assert!(
        output.contains("belongs to the tag"),
        "the refusal must explain that the `v` is the tag's, not the \
         version's:\n{output}"
    );
}
